In [4]:
import numpy as np

In [5]:
np.__version__

'1.26.4'

When ever we are using . notation, dot notation, we are trying to access the methods within a class

`numpy.__version__`  attribute within the numpy class



In [ ]:
python_list = [1,2,3,"string",6.7]


numslist = [x for x in range(10)]
print(numslist)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
print(numslist*3)
print(type(numslist))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [ ]:
arr1 = np.array([1,2,3,4,5])
print(arr1)


[1 2 3 4 5]


In [16]:
print(arr1*3)
print(type(arr1))

[ 3  6  9 12 15]
<class 'numpy.ndarray'>


In [26]:
arr1D = np.array([1,  2,  3])
print(arr1D,"\n",arr1D.ndim)

[1 2 3] 
 1


In [24]:
arr2D = np.array([[1,  2,  3],
                  [1,  2,  3]])

print(arr2D,"\n",arr2D.ndim)

[[1 2 3]
 [1 2 3]] 
 2


In [25]:
arr3D = np.array([[[1,  2,  3],[1,  2,  3]],
                  [[1,  2,  3],[1,  2,  3]]])

print(arr3D,"\n",arr3D.ndim)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]] 
 3


In [ ]:
# ndim works on objects, and checks their dimensions

print(f"dimensions are: {arr1D.ndim}")

print(f"dimensions are: {arr2D.ndim}")

print(f"dimensions are: {arr3D.ndim}")


# using np.shape method, for checking the dimensions of an array!!!
# (rows, columns)

print(f"dimensions are: {np.shape(arr1D)}")

print(f"dimensions are: {np.shape(arr2D)}")

print(f"dimensions are: {np.shape(arr3D)}")

np.ndim(arr1D)
arr1D.shape

# size, how large array is, how many elements there are in the array


# 

arr1D.dtype



dimensions are: 1
dimensions are: 2
dimensions are: 3
dimensions are: (3,)
dimensions are: (2, 3)
dimensions are: (2, 2, 3)


dtype('int32')

int8 

int16

int32

int64

In [47]:
shape1D = arr1D.ndim
shape1D

size1D = arr1D.size
size1D

size2D = arr2D.size
size2D

size3D = arr3D.size
size3D


12