- data - 

    - iris: [sepal length, sepal width, species ]
    - titanic: [ pclass sibling spouse fare age gender survival ]
    - tips: [ ]
    - penguins: [ species island lenght widths]

Columns = vectors 

In [152]:
list2= [3,4,5 , 'idrees', 4.5, [3, ['a','b'],5]]

list2[5][1][0]

'a'

In [153]:
vectorx = [3,4,[5,6,7],3]

vectorx[2][1]

6

In [154]:
vector1 = [10,4,10]

vector2 = [20,4,10]

vector3 = [30,4,10]

sum(vector1)
len(vector1) # number of element


3

In [155]:
import numpy as np

arr = np.array(vector1)
arr

arr.max()
arr.min()
arr.mean()
arr.var() # 8.0
arr.std() # 2.82

2.8284271247461903

In [156]:
vector1 = [10,4,10]
vector2 = [20,4,10]
vector3 = [30,4,10]

matrix = [vector1, 
          vector2, 
          vector3] # 0 1 2

matrix = [[10,4,10],
          [20,4,10],
          [30,4,10]]

matrix

# how to check the dimensions?

 # [2,4,10] as a result
 # 2 as a result


[[10, 4, 10], [20, 4, 10], [30, 4, 10]]

In [158]:
matrix = [[10,4,10], # 0
          [20,4,10], # 1   # 0
          [30,4,10], # 2   # 1
          [30,4,10]] # 3

matrixarr = np.array(matrix)

In [166]:
matrix[0:2][ : ] # row  x  column

[[10, 4, 10], [20, 4, 10]]

In [167]:
type(matrixarr)

matrixarr.ndim

matrixarr[1][2]

#  1 2
matrixarr[1:3][2] # rows 

IndexError: index 2 is out of bounds for axis 0 with size 2

In [168]:
matrixarr[1][2]

10

In [169]:
matrixarr * 2 # scalar multiplication

# scaler operations with arrays
# 

matrixarr.ndim
matrixarr.shape # how many rows and columns

# rows  x  columns



(4, 3)

In [ ]:
# broadcastinggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg

matrixarr + 100

array([[110, 104, 110],
       [120, 104, 110],
       [130, 104, 110],
       [130, 104, 110]])

In [ ]:
a = np.array([[1, 3, 5, 6],
             [2, 8, 7, 9]]
             )
b = np.array([[10], 
              [100]])

a - b
a / b
a + b
a * b
a @ b 

array([[ 11,  13,  15,  16],
       [102, 108, 107, 109]])

In [ ]:
variance = np.array([145325, 423542, 24355, 3523456])
n = np.array([145, 542, 355, 3456])

In [ ]:
((variance)**0.5) .round(2)

array([ 381.22,  650.8 ,  156.06, 1877.09])

In [ ]:
covariance = np.array([145325, 423542])

n = np.array([145, 542, 355, 3456])

stdx , stdy = np.array([ 381.22,  650.8])

stdx
stdy


r = covariance/(stdx*stdy)
r

array([0.58575649, 1.70715621])

In [ ]:
x = np.array([[1,4,1],
              [2,5,2]])

w = np.array([10,10,10])

w2 = np.array([[10,2,3],
              [10,2,3],
              [10,2,3]])

matmultiply_xw = np.dot(x,w)
matmultiply_xw

array([60, 90])

In [170]:
matmultiply_xw2 = np.dot(x,w2)
matmultiply_xw2

array([[60, 12, 18],
       [90, 18, 27]])

In [ ]:
matmultiply_xw2 = x @ w2
matmultiply_xw2

array([[60, 12, 18],
       [90, 18, 27]])

In [ ]:
matmultiply_xw2 = np.matmul(x,w2)
matmultiply_xw2

array([[60, 12, 18],
       [90, 18, 27]])

A = 
2  3  4
6  7  8
3  2  3

shape = 3 x 3   2 x 3

B = 
5  5  5
2  2  2

shape = 2 x 3

B  x  A 

2 x 3  =  3 x 3

In [ ]:
A = np.array(
[[2 , 3 , 4],
[6 , 7 , 8],
[3 , 2 , 3]]
)

B = np.array(
[[5 , 5 , 5],
[2 , 2 , 2]]
)

B @ A   
# matrix multiplication is not commutative




array([[55, 60, 75],
       [22, 24, 30]])

- arrays are faster, huge data, 
- list arrays for 100K numbers
- arrays significatly
- array methods, help us do linear alebra



In [ ]:
import numpy as np

hetero = np.array([1 , 2, '1222', 'idrees', 5.4])
hetero

hetero = np.array([1 , 2,3, 5, 5])
hetero.dtype

hetero = np.array(['idrees','ibrahim','mel', 'hazira'])
hetero.dtype

hetero[2]

'mel'

In [185]:
A = np.array(
[[5 , 5 , 5],
[2 , 2 , 2],
[5 , 5 , 5]]
)

B = np.array(
[[3 , 3 , 3],
[3 , 3 , 3],
[3 , 3 , 3]]
)

In [186]:
print("Matrix Multiplication: \n",A @ B,"\n")
print("Simple Array Multiplication: \n",A * B)

print('____________________ B x A')

print("Matrix Multiplication: \n",B @ A,"\n")
print("Simple Array Multiplication: \n",B * A)

Matrix Multiplication: 
 [[45 45 45]
 [18 18 18]
 [45 45 45]] 

Simple Array Multiplication: 
 [[15 15 15]
 [ 6  6  6]
 [15 15 15]]
____________________ B x A
Matrix Multiplication: 
 [[36 36 36]
 [36 36 36]
 [36 36 36]] 

Simple Array Multiplication: 
 [[15 15 15]
 [ 6  6  6]
 [15 15 15]]
